wordpress:
    structure:
        content: app
        wordpress: wordpress
    database:
        host: 127.0.0.1
        user: root
        password: ~
        name: wordpress
    extensions:
        - Betterpress\Extensions\BetterpressFramework\BetterpressFrameworkExtension
        - Acme\Extensions\HelloWorld\HelloWorldExtension
